### ISSUE TITLE
Use of useFallbackTranslation results in faulty language selection

### ISSUE THREAD

**Issue by krokofant** [ngneat/transloco#287] opened 2020-05-26 21:22 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Setting `useFallbackTranslation` causes transloco to assume that the fallback language is scoped when it's not, which results in a requested `lang` that has a `/` prefix. E.g. `/en`

1. Specify a fallback `fallbackLang: 'en'`
2. Setting active language to `sv-SE` (it should not be listed as available either)
3. Have a missing translation for `foo` in `sv-SE`
4. Notice that the HttpLoader `getTranslation` is first called with `sv-SE`
5. Notice that the HttpLoader `getTranslation` is then called with `/en`

Note that the default HttpLoader most likely survives as two slashes often works:
```typescript
@Injectable({ providedIn: 'root' })
export class TranslocoHttpLoader implements TranslocoLoader {
  constructor(private http: HttpClient) {}

  getTranslation(lang: string) {
    return this.http.get<Translation>(`/assets/i18n/${lang}.json`);
  }
}
```
With this loader the computed url would be `/assets/i18n//en.json`.

If the loader loads translations from an api like `/lang=${lang}` it will result in `/lang=/en` and perhaps break.

## Expected behavior
A language should only be considered scoped if the language name contains a `/`.
A fallback language maybe shouldn't require to be under the primary language scope. Currently `foo/bar` will fallback to `foo/${lang}`.

This function that checks for scope should be checking if the language id contains a `/`:
```typescript
  _isLangScoped(lang: string) {
    return this.getAvailableLangsIds().indexOf(lang) === -1;
  }
```

## Workaround
Just assume the requested language exists just to avoid it being considered scoped:
```typescript
transloco.setAvailableLangs([locale.language]);
const availableLanguages = transloco.getAvailableLangs() as string[];
if (!availableLanguages.includes(locale.language)) {
	// Just assume this language is available somewhere
	transloco.setAvailableLangs([...availableLanguages, locale.language]);
}
transloco.setActiveLang(locale.language);
```
Though this makes it harder to actually use scoped translations

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shaharkazaz** [comment] 2020-05-27 08:17
@krokofant can you share your entire transloco config?

**Comment by krokofant** [comment] 2020-05-27 09:40
@shaharkazaz Here is a reproduction on Stackblitz. On the default linked template version `2.0.2` was used which does not have the issue. The latest `2.17.1` does have the issue. Check the console log.

https://stackblitz.com/edit/transloco-example-qlph5x?file=src%2Fapp%2Fapp.module.ts

**Comment by krokofant** [comment] 2020-06-03 08:24
@shaharkazaz Did you see the reproduction? I could supply a PR if I get some direction

**Comment by shaharkazaz** [comment] 2020-06-03 09:28
@krokofant sorry missed that, I'll take a look today and a PR is always welcome! 😄

**Comment by shaharkazaz** [comment] 2020-06-04 11:28
@krokofant I see there is an issue with your configuration.
You need to declare all the languages you are going to use in your app.
In the reproduction you provided you declared: `availableLangs: [{ id: 'en', label: 'English' }, { id: 'es', label: 'Spanish' }],` 
If you change it to: `availableLangs: [{ id: 'sv-SE', label: 'SVE' }, { id: 'en', label: 'English' }, { id: 'es', label: 'Spanish' }],` you will see the issue is resolved.

**Comment by krokofant** [comment] 2020-06-04 21:06
@shaharkazaz In my real application I have provided a fallback to an api and the web application does not know all the languages that are supported there.

I have configured a fallback but this issue makes is to that any language that isn't known before-hand to be support will be assumed to be scoped - even if it does not contain a `/`. If I can have a handler that is responsible for fetching whatever translations transloco wants then I should not have to tell transloco which these are before hand.

My current workaround is has to explicitly fail the scoped language, and then process the intended language after that one fails:

```typescript
@Injectable({ providedIn: 'root' })
export class TranslocoHttpLoader implements TranslocoLoader {
	constructor(private http: HttpClient) {}

	private fetchLanguageFromBackend(lang: string) {
		return this.http.get<Translation>(`/api/Translations?lang=${lang}`);
	}

	getTranslation(lang: string) {
		// Skip faulty scoped language
		if (lang.length && lang[0] === '/') {
			return throwError(`Ignore wrongly scoped language`);
		}

		if (precompiledLanguages.includes(lang)) {
			return this.http.get<Translation>(`assets/i18n/${lang}.json`);
		} else if (LANGUAGE_SUB_TAG_REGEX.test(lang)) {
			return throwError(`Fallback ${lang} to parent language`);
		}

		return this.fetchLanguageFromBackend(lang);
	}
}
```

```typescript
@Injectable()
export class CustomFallbackStrategy implements TranslocoFallbackStrategy {
	getNextLangs(failedLang: string) {
		const fallbacks = ['en'];
		if (!LANGUAGE_SUB_TAG_REGEX.test(failedLang)) return fallbacks;

		return [failedLang.match(LANGUAGE_SUB_TAG_REGEX)[1]].concat(fallbacks);
	}
}
```

1. It has a list of precompiled languages
2. It tries to fetch from these
3. It tries to fallback to a parent language sv-SE to sv if sub language is missing
4. If there still is no match it fetches translations for an api

So what I want is for an unknown language to be able to have a fallback, without working around the assumed scope with throwing an error.

**Comment by shaharkazaz** [comment] 2020-06-08 15:11
@krokofant I see your point.
I'll merge your PR and release the new version.

**Comment by shaharkazaz** [comment] 2020-06-08 16:13
@krokofant Seems like this is a breaking change.
If there is a point where you do know the languages you add them at runtime via the API, if not you can still use your solution.
Also, please check that your tests are passing before opening a PR (we also have a pre-push hook for it, you might have bypassed it)

**Comment by krokofant** [comment] 2020-06-09 18:23
@shaharkazaz Thank you for your attention. I'll create a new PR when I have the time and I'll make sure to check the tests. Last time I just submitted the change via GitHub.

**Comment by shaharkazaz** [comment] 2020-06-10 08:48
@krokofant sure thing, but as I said it's a breaking change.
I'm closing this, for now, feel free to reopen or contact me directly via [gitter](https://gitter.im/ngneat-transloco/lobby)

**Closed by shaharkazaz** 2020-06-10 08:48 UTC
