### ISSUE TITLE
Bug(scope): nx monorepo translate function isn't working

### ISSUE THREAD

**Issue by Choupa-web** [ngneat/transloco#629] opened 2023-02-20 14:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

No

### Current behavior

I'm using NX monorepo, with 3 angular apps ( 1 master and 2 childs). In the master app all is working fine.
For the child app, the translate function is not translating at all in the ts file. While it is working correctly in the template (html).

In the console of my web browser I can see that it takes language json files from my master app. The language json files of my child app are handled by webpack.

### Expected behavior

I have to be able to use function translate inside ts file of the components which are in my child app.

### Please provide a link to a minimal reproduction of the bug

NA

### Transloco Config

```markdown
my transloco-root.module.ts:
export const loader = ['en', 'fr'].reduce((acc, lang) => {
  acc[lang] = () => import(`../assets/i18n/${lang}.json`);
  return acc;
}, {});

@NgModule({
  exports: [TranslocoModule],
  providers: [
    {
      provide: TRANSLOCO_CONFIG,
      useValue: translocoConfig({
        availableLangs: ['fr', 'en'],
        defaultLang: 'fr',
        // Remove this option if your application doesn't support changing language in runtime.
        reRenderOnLangChange: true,
        prodMode: environment.production as unknown as boolean
      })
    },
    { provide: TRANSLOCO_SCOPE, useValue: { scope: 'dashboard', loader } }
  ]
})
export class TranslocoRootModule {
}
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 4.2.2
Angular: 15.1.5
Node: 18.12.1
Package Manager: 8.19.2
OS: ubuntu
```

### Browser

```markdown
Chrome v110.0.5481.96
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment] 2023-02-20 14:36
@Choupa-web Please provide a reproduction link

**Comment by guzmanoj** [comment] 2023-03-01 09:32
Probably because your translations are not fully loaded yet?
I noticed that your are using scoped translations (per module) this an `async` operation by nature, and the `translate()` function is sync. So, it's up to you to ensure that the module scoped translations are ready before using the `translate()` function.

**Comment by shaharkazaz** [comment] 2023-03-04 16:13
@Choupa-web Closing this for now as to @guzmanoj comment + no reproduction link which is mandatory.
Feel free to re-open the issue if it makes sense, only reopen it with a valid reproduction.

**Closed by shaharkazaz** 2023-03-04 16:13 UTC
Labels: needs reproduction
