### ISSUE TITLE
Error: No provider for InjectionToken TRANSLOCO_TRANSPILER!

### ISSUE THREAD

**Issue by DoronTorangy** [ngneat/transloco#296] opened 2020-06-18 12:38 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I use TranslocoRootModule in my app module, when i run my application it works perfectly.
like this:

`@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    HttpClientModule,
    TranslocoRootModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

But when i try to test `AppComponent` i do this module initiation:

`
beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule,
        TranslocoRootModule
      ],
      declarations: [AppComponent]

    }).compileComponents()
  }))
`

And then when i run my tests i get this:

`
NullInjectorError: R3InjectorError(DynamicTestModule)[TranslocoService -> InjectionToken TRANSLOCO_TRANSPILER -> InjectionToken TRANSLOCO_TRANSPILER]: 
	  NullInjectorError: No provider for InjectionToken TRANSLOCO_TRANSPILER!
	error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'TranslocoService', 'InjectionToken TRANSLOCO_TRANSPILER', 'InjectionToken TRANSLOCO_TRANSPILER' ] })
	    at <Jasmine>
	    at NullInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:1085:1)
	    at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:16955:1)
	    at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:16955:1)
	    at injectInjectorOnly (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:940:1)
	    at Module.ɵɵinject (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:950:1)
	    at Object.TranslocoService_Factory [as factory] (http://localhost:9876/_karma_webpack_/node_modules/@ngneat/transloco/__ivy_ngcc__/fesm2015/ngneat-transloco.js:1341:152)
	    at R3Injector.hydrate (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:17193:42)
	    at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:16943:1)
	    at NgModuleRef$1.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:36329:1)
	    at Object.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:33972:1)
`

I don't get how when i run my app it works, but when running tests it doesnt, i also tried to follow the transloco tutorial for testing and did this:

`
function getTranslocoModule(config: Partial<TranslocoConfig> = {}) {
  return TranslocoTestingModule.withLangs(
    {he, en},
    {
      availableLangs: ['he', 'en'],
      defaultLang: 'he',
      fallbackLang: 'he',
      reRenderOnLangChange: true,
      ...config
    },
  ).providers = [{
    provide: TRANSLOCO_TRANSPILER, useClass: DefaultTranspiler
  }]
}

beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule,
        getTranslocoModule()
      ],
      declarations: [AppComponent]

    }).compileComponents()
  }))
`

also didnt work....

## Expected behavior

Transloco module should be injected normally without any exceptions

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment] 2020-06-28 07:50
@DoronTorangy The code from your example seems ok, could you please create a reproduction so I can debug it and see what the problem is?

**Comment by DoronTorangy** [comment] 2020-06-28 08:18
@itayod later this day i'll do it

**Comment by shaharkazaz** [comment] 2020-07-23 06:59
@DoronTorangy is this still relevant? can you provide a reproduction?

**Comment by shaharkazaz** [comment] 2020-08-01 12:40
@DoronTorangy Closing this, if it's still relevant please re-open with a small reproduction.

**Closed by shaharkazaz** 2020-08-01 12:40 UTC

**Comment by yunusyerli1** [comment] 2022-07-25 13:22
Same problem with me? Any ideas?

**Comment by shaharkazaz** [comment] 2022-07-26 06:46
@yunusyerli1 If you provide a reproduction I can try and resolve this.

**Comment by yunusyerli1** [comment] 2022-07-26 06:56
> @yunusyerli1 If you provide a reproduction I can try and resolve this.

I solved it. Thanx for you answer.

**Comment by shaharkazaz** [comment] 2022-07-31 12:15
@yunusyerli1 Can you share what was the issue for future users? 😄

**Comment by yunusyerli1** [comment] 2022-07-31 12:53
TranslocoModule was registered in SharedModule provider but when I delete SharedModule, I didnt register TranslocoModule to AppModule. This was the issue. After registering TranslocoModule to AppModule, The problem has gone.

**Comment by rami-almofleh** [comment] 2023-08-23 06:55
i have the same here. Any solution? i have already imported "TranslocoModule" in my app.module. 
this error came as i update from 4.1.1 to 5.0.6

**Comment by pnocera** [comment] 2023-08-23 07:01
same here. angular 16.1.0 transloco 5.0.7

**Comment by shaharkazaz** [comment] 2023-08-23 07:08
@rami-almofleh @pnocera The TranslocoModule doesn't provide these providers. please look at [the docs](https://ngneat.github.io/transloco/docs/getting-started/installation), you need to use `provideTransloco`.

**Comment by rakshitongit** [comment] 2024-02-21 08:37
> @rami-almofleh @pnocera The TranslocoModule doesn't provide these providers. please look at [the docs](https://ngneat.github.io/transloco/docs/getting-started/installation), you need to use `provideTransloco`.

Is the documentation still up? or has it been moved somewhere?

**Comment by shaharkazaz** [comment] 2024-02-21 08:39
@rakshitongit The docs are up, just in a new home 🙂 
I updated the comment.

**Comment by hlovdal** [comment] 2026-05-11 21:19
The document link now at https://jsverse.gitbook.io/transloco/getting-started/installation.
