### ISSUE TITLE
scoped translations are not loaded if lazy loaded component includes component from another module

### ISSUE THREAD

**Issue by pelssersconsultancy** [ngneat/transloco#193] opened 2019-12-09 18:00 UTC
## I'm submitting a 

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
App module redirects to lazy component from lazyloaded-feature.module.
This lazy loaded feature module contains translations for its own components. This seems to work as documented.

However, this lazy component contains another component reference from another lazyloaded-shared-ui.module

This module also contains its own translations but they are not properly loaded.

## Expected behavior

The scopeLoaded from lazyloaded-shared-ui.module provides its own translation scope and I would expect this scope to be loaded properly.

## Minimal reproduction of the problem with instructions

Please see this minimal setup of the issue in this github repo:
https://github.com/pelssersconsultancy/transloco-poc

## Environment

<pre><code>
Angular version: 8.2.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by itayod** [comment] 2019-12-10 18:45
duplicate of #172

**Closed by itayod** 2019-12-10 18:45 UTC
