### ISSUE TITLE
Feature request for multiple scopes using Angular Modules

### ISSUE THREAD

**Issue by boban984** [ngneat/transloco#222] opened 2020-01-23 14:34 UTC
## I'm submitting a feature request

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have an angular app with one main module and 2 feature modules, loaded eagrly.
The main translation json gets loaded and the last module's json file (in this case CMSModule). 
 
![Screenshot_2](https://user-images.githubusercontent.com/1124994/72992945-db5f6c80-3df4-11ea-9495-f7b98728d393.jpg)

## Expected behavior
It would be nice to have the ability to use scoped translations on multiple modules, limiting it just one module makes the current feature useless.
So the expected behaviour would be to load 3 json files for all 3 modules, instead of just loading 2.

## Environment

<pre><code>
Angular version: 9.0.0-rc.9
Transloco version: 2.12.4
Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.3.1
- Platform:  Windows 10

**Comment by itayod** [comment] 2020-01-24 15:35
Duplicate of #202

**Closed by itayod** 2020-01-24 15:35 UTC
