### ISSUE TITLE
Migrate from ngx-translate

### ISSUE THREAD

**Issue by jochenjonc** [ngneat/transloco#252] opened 2020-03-05 10:26 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

After running the migration from ngx-translate to transloco I noticed that a lot of translations did not work anymore.

The thing is that in my code I fetch a bunch of translations in a single statement, by passing the translation keys as array.

```typescript
this.translateService.stream(['translation.key.one', 'translation.key.two']);
```
After converting the array remains in the transloco variant of the code, but this no longer works.

```typescript
this.translateService.selectTranslate(['translation.key.one', 'translation.key.two']);
```

## Expected behavior

First of all, I'm not sure what the equivalent of the array of keys is in transloco, but I think it should have been the following.

```typescript
this.translateService.getTranslateObject('translation.key', {
  one: {},
  two: {}
});
```

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [x] Chrome (desktop) version 80
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 13.10.1
- Platform:  Windows

Others:

</code></pre>

**Comment by ArielGueta** [comment] 2020-03-09 12:43
`'translation.key.one', 'translation.key.one'` returns strings or objects?

**Comment by jochenjonc** [comment] 2020-03-10 17:09
> `'translation.key.one', 'translation.key.two'` returns strings or objects?

they return strings

**Comment by ArielGueta** [comment] 2020-03-10 17:53
I tried it and it works. https://stackblitz.com/edit/ngneat-transloco-hzabmt?file=src%2Fapp%2Fhome%2Fhome.component.ts

**Comment by ArielGueta** [comment] 2020-03-10 17:54
`stream` and `selectTranslate` returns an observable. You need to subscribe.

**Comment by shaharkazaz** [comment] 2020-03-17 07:14
@jochenjonc just to clarify, when passing several keys in `ngx-translate` `stream` function you get an object back? in transloco passing an array will resolve in an array with the translated strings.

**Comment by jochenjonc** [comment] 2020-03-18 09:09
> I tried it and it works. https://stackblitz.com/edit/ngneat-transloco-hzabmt?file=src%2Fapp%2Fhome%2Fhome.component.ts

This works, and returns an array but the key is not availble, you cannot do the following:

```typescript
console.log(v['some.nested.key'])
```

This works, but is not safe to use if you have a lot of keys:

```typescript
console.log(v[0])
```

**Comment by jochenjonc** [comment] 2020-03-18 09:13
> @jochenjonc just to clarify, when passing several keys in `ngx-translate` `stream` function you get an object back? in transloco passing an array will resolve in an array with the translated strings.

Correct, that is way I was wondering if it shouldn't be changed to:

```typescript
this.translateService.getTranslateObject('translation.key', {
  one: {},
  two: {}
});
```

**Comment by shaharkazaz** [comment] 2020-03-19 07:53
@jochenjonc I see. I will add a note in the migration file so people will know they need to change this to the `selectTranslateObject` (since stream returns an observable).
This will not be part of the migration script as of now, but you are welcome to extend it and create a PR 🙂

**Comment by swayf** [comment] 2020-03-22 11:29
First of all thank you for the awesome lib =)
I am wondering, is any alternative to ngx-translate "extract" marker..
It is just empty function, but some strings can be marked in code without translation.
In transloco I can do it within special commend /** t(term) */ but in this case I have to repeat this term twice.. once in code and second time in comment. am I right? or there is something like 'extract' in ngx-translate?

thank you for support

**Comment by shaharkazaz** [comment] 2020-03-22 22:00
@swayf Thanks for your support! 
Let's take this in [our gitter channel](https://gitter.im/ngneat-transloco/lobby) since it's not really related to this issue, you can always ask for help there 🙂

**Comment by shaharkazaz** [comment] 2020-03-23 08:56
@jochenjonc I have updated [our ngx-migration doc](https://app.gitbook.com/@netbasal/s/transloco/schematics/migrate/migration-from-ngx-translate).
Closing this, thanks again for the report, feel free to open a PR and implement the functionality 🙂

**Closed by shaharkazaz** 2020-03-23 08:56 UTC

**Comment by FloNeu** [comment] 2020-09-02 12:23
Not directly related to original question, but to the ngx-translation migration - I haven't found anything on defining translation-keys in source-code. 

For example with ngx-translate I have a service and define a member:
`public readonly traslation_key( 'test' )` 
which then creates the key 'test' when running the e cli extractor tool. Is there something like this in transloco, or can i only define keys using the structural directive?

**Comment by shaharkazaz** [comment] 2020-09-02 12:39
@FloNeu Have you seen the [transloco keys manager](https://github.com/ngneat/transloco-keys-manager)

**Comment by FloNeu** [comment] 2020-09-02 13:23
@shaharkazaz first, thx for the fast response... 

yes, i have - but I took a look at it again... maybe I didn't get it first - are you referring to section 
'dynamic keys' and that I should use these 
`*/** t(key.typeOne.postfix, key.typeTwo.postfix) */`-comments?
for example, like:
`/** t( test ) */
public readonly test
`
to have it picked up by the extractor? But how can I use the scope-features when I have this in
a service where there isn't a 'provider' section in the @Injectable()-Decorator?

My use-case is that i have a service-containing members representing my application routes, like so: 

```
@Injectable( { providedIn: 'root' } )
export class RouteTranslationKeys {
  /** t(  route_home ) */  // Ok, yes that worked
  public readonly ROUTE_HOME = translation_key( 'route_home );
  // Maybe add as a feature request that it would be cool to have it also 
  // work with function-style in code to have it clear that this performs a function
  // and people unfamiliar with transloco maybe delete translation-key comments
  public readonly ROUTE_LOGIN = translation_key( 'route_login' );
  constructor( ) {}
}
```
and i now try to get them into their own 'scope'-file.

**Comment by shaharkazaz** [comment] 2020-09-03 18:30
@FloNeu I think that [this feature](https://github.com/ngneat/transloco-keys-manager/issues/59) is what you are looking for.

**Comment by FloNeu** [comment] 2020-09-05 12:20
Yes indeed... that means it will be available soon. very nice... just short
question because I still have problems.
Key-Extractor only picks up keys from comments? or should it also pick up
the keys from normal use
within the t( 'key' ) function? Because i can't get this to work

Am Do., 3. Sept. 2020 um 20:30 Uhr schrieb Shahar Kazaz <
notifications@github.com>:

**Comment by shaharkazaz** [comment] 2020-09-05 14:33
@FloNeu Let's leave this thread since it's no longer related to the original issue.
If you have any questions you can try getting help in our [gitter lobby](https://gitter.im/ngneat-transloco/lobby) or open an issue with reproduction in the [keys manager repo](https://github.com/ngneat/transloco-keys-manager).

**Comment by FloNeu** [comment] 2020-09-05 17:23
Right. i will delete my comments shortly...
