### ISSUE TITLE
test failing with "Cannot read property 'reRenderOnLangChange' of undefined"

### ISSUE THREAD

**Issue by stephengeorgewest** [ngneat/transloco#374] opened 2020-11-30 20:27 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>
Not sure if bug or documentation issue or support request. I'm not sure if I'm setting it up wrong, or if it is an actual bug. I worked around the issue, but I'll dump some stuff here to see if it helps at all.

## Current behavior
Test fails throwing error

<pre><code>Summary of all failing tests
 FAIL  src/app/contacts/components/contact-card/contact-card.component.spec.ts (32.098s
  ● ContactCardComponent › should create

    TypeError: Cannot read property 'reRenderOnLangChange' of undefined

      at shouldListenToLangChanges (node_modules/@ngneat/transloco/bundles/ng:/@ngneat/
      at new TranslocoPipe (node_modules/@ngneat/transloco/bundles/ng:/@ngneat/transloc
      at TranslocoPipe_Factory (node_modules/@ngneat/transloco/bundles/ngneat-transloco
      at ɵɵpipe (../packages/core/src/render3/pipe.ts:55:24)
      at ContactCardComponent_Template (ng:/ContactCardComponent.js:78:9)
      at executeTemplate (../packages/core/src/render3/instructions/shared.ts:559:5)
      at renderView (../packages/core/src/render3/instructions/shared.ts:351:7)
      at renderComponent (../packages/core/src/render3/instructions/shared.ts:1759:3)
      at renderChildComponents (../packages/core/src/render3/instructions/shared.ts:154
      at renderView (../packages/core/src/render3/instructions/shared.ts:380:7)
      at ComponentFactory.Object.<anonymous>.ComponentFactory.create (../packages/core/
      at initComponent (../packages/core/testing/src/r3_test_bed.ts:354:28)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist
      at Object.onInvoke (../packages/core/src/zone/ng_zone.ts:326:29)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)
      at NgZone.Object.<anonymous>.NgZone.run (../packages/core/src/zone/ng_zone.ts:180
      at TestBedRender3.Object.<anonymous>.TestBedRender3.createComponent (../packages/
      at Function.Object.<anonymous>.TestBedRender3.createComponent (../packages/core/t
      at createSpectator (node_modules/@ngneat/spectator/bundles/ng:/@ngneat/spectator/
      at node_modules/@ngneat/spectator/bundles/ng:/@ngneat/spectator/lib/spectator/cre
      at src/app/contacts/components/contact-card/contact-card.component.spec.ts:32:21
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)

  ● ContactCardComponent › should create

    expect(received).toBeTruthy()

    Received: undefined

      35 | 
      36 |     it("should create", () => {
    > 37 |         expect(component).toBeTruthy();
         |                           ^
      38 |     });
      39 | });
      40 |

      at src/app/contacts/components/contact-card/contact-card.component.spec.ts:37:27.ts:37:27
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)

Test Suites: 1 failed, 447 skipped, 1 of 448 total
Tests:       1 failed, 2873 skipped, 2874 total
Snapshots:   0 total
Time:        188.737s
Ran all test suites with tests matching "ContactCardComponent".</code></pre>

It is in a component that uses TranslocoPipe, which seems to be missing a config:
![image](https://user-images.githubusercontent.com/1442484/100649112-2e505d00-32ff-11eb-96d8-61cba642b224.png)

Similar working component:
![image](https://user-images.githubusercontent.com/1442484/100649999-80de4900-3300-11eb-8fbf-78bd169e9013.png)

It was failing when I provided a provideMockTranslate() ... which I didn't actually need,
![image](https://user-images.githubusercontent.com/1442484/100660374-2c8e9580-330f-11eb-97b2-c057454e64b3.png)
![image](https://user-images.githubusercontent.com/1442484/100656557-21853680-330a-11eb-829c-1ea98fdcce78.png)
This function worked fine for components that only did translations in the typescript file using the TranslocoService, but failed when loaded while using the translate pipe.

I tried putting in some things in that useValue that I found around the internet, which seemed to correspond to the config, but it didn't help:
![image](https://user-images.githubusercontent.com/1442484/100656932-b851f300-330a-11eb-83c1-a18d632eaed9.png)
My fix was to not provide the TranslocoService for tests of components that use the pipe. I may have to revisit this once we have components that use both the service and the pipe, I'm not sure this is related to this specific issue, but maybe it can help someone.

## Expected behavior
I wasn't expecting config to be undefined, since config was in the TranslocoTestingModule just as the docs described. https://ngneat.github.io/transloco/docs/unit-testing

## Environment

<pre><code>
Angular version: 10.0.10

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 13.7.0  
- Platform: Windows 

Others:

Jest version 9.0.0
</code></pre>

**Comment by itayod** [comment] 2020-12-01 14:57
Hi @stephengeorgewest could you please create a reproduction of this issue?

**Comment by iiceman40** [comment] 2020-12-02 20:02
I am having the same problem. It works in most unit tests for our components but some do not work and throw this error. I havn't figured out what the difference is yet.

We are using Angular 11.0.2 and Transloco in version 2.17.3.

**Comment by shaharkazaz** [comment] 2020-12-17 20:25
@iiceman40 @stephengeorgewest  There were some changes related to the test module in the last version (v2.20.0) can you please check if it still happens? and it does reproduce can you please provide a reproduction? 🙂

**Comment by stephengeorgewest** [comment] 2021-01-07 23:58
I updated to 2.20.0 and reverted my "fixes". 
![image](https://user-images.githubusercontent.com/1442484/103957337-be0bd700-5107-11eb-8534-374e0a23b96f.png)

I did go into `getTranslocoTestingModule` to see if that could be something, and noticed "withLangs is deprecated: - use forRoot instead (deprecation)" could that be related?
![image](https://user-images.githubusercontent.com/1442484/103957567-35da0180-5108-11eb-81f8-548f4dbffa8e.png)
config defaults to a empty object, and doesn't change between the broken/non broken versions, so I doubt this is the issue.

**Comment by shaharkazaz** [comment] 2021-01-11 10:42
@stephengeorgewest 
It's not related to the deprecation warning since `withLangs` is still supported.
please provide a reproduction so we can better understand the issue.

**Comment by krzyhan** [comment] 2021-01-18 15:03
@stephengeorgewest I guess your `provideMockTranslate` should contain property `config` :
![image](https://user-images.githubusercontent.com/20922676/104931339-8bcf6480-59a6-11eb-9f0c-86cc2176b8a0.png)

so those three should be in `config` prop:
![image](https://user-images.githubusercontent.com/20922676/104931397-a1dd2500-59a6-11eb-9de2-6ce16dd23931.png)

**Comment by iiceman40** [comment] 2021-01-21 14:37
@shaharkazaz  I just updated to `2.20.0` and can confirm, that the error still occurs. Our mock module looks like this:

```
const en = {};
export const TranslocoMockModule = TranslocoTestingModule.withLangs(
  {en},
  {
    defaultLang: 'en'
  }
);
```

@krzyhan I tried adding those properties but it doesn't change anything. You don't seem to use them yourself either (except the defaultLang, as we do, too). The error message says `Cannot read property 'reRenderOnLangChange' of undefined` so it's not about the properties in the config but the whole config that seems to be missing.

I didn't have time to try to reproduce it yet. For me the error happens in a big project where I can't really extract a reproduction that easily :-/

**Comment by shaharkazaz** [comment] 2021-01-30 09:29
@iiceman40 It's hard for me to help you without actually seeing the code & issue.
I would suggest trying to remove all manual mocks (if exists) and try to isolate the issue, from v2.20.0 the service is bootstrapped by Transloco.

The reproduction can be very small, I understand that creating one from a big repo can be challenging but I'm afraid that's the only way I can assist further.

**Comment by erikmom** [comment] 2021-02-11 14:19
We had this issue as well, however (after some thorough debugging session) we found out that we still used a mocked TranslocoService in one of our TestModuleMetadata objects that we accidentally migrated from a previous i18n library:

`{ provide: TranslocoService, useClass: MockTranslocoService }`

After removing this provider it worked. We now only use the `getTranslocoModule()` to get transloco working in our test suite.

**Comment by shaharkazaz** [comment] 2021-03-12 10:10
@stephengeorgewest  @iiceman40, any updates on reproducing the issue?  🙂 
If you don't think you'll get to it anytime soon, please close the issue and reopen it once you provide the reproduction.

**Comment by iiceman40** [comment] 2021-03-14 17:33
Okay, I finally took the time and gave this a shot.

The problem occurs when I use the transloco pipe and the TranslocoService in a component. If I write the unit test I add the TranslocoTestingModule so that the test won't fail because of the missing pipe. Next I am mocking the TranslocoService to make it return a mocked translation that I can refer to in my expect statement. If I now run the test all thests in this component fail with the "Cannot read property 'reRenderOnLangChange' of undefined" error.

Check out  [https://github.com/iiceman40/TranslocoTest](https://github.com/iiceman40/TranslocoTest) and simply run `ng test`.

**Comment by shaharkazaz** [comment] 2021-04-03 13:12
@iiceman40 The issue is caused because you are incorrectly mocked the TranslocoService.
If you decided to provide your own implementation of a service in a test you are also responsible for making sure that it's initialized correctly and in our case, you need the `TranslocoService` to have a config.

Adding config to the service definition resolved the issue (from your reproduction):
```typescript
  const translocoService: SpyObj<TranslocoService> = jasmine.createSpyObj(
    'translocoService',
    {
      // Note that I also changed the returned text to match the test case 🙂 (mock-translation => mock-text).
      selectTranslate: of('mock-text'), 
      config: {}
    }
  );
```

I do recommend working with the testing module as presented in the documentation.
Also, it could be great if you can explain why are you testing a mocked returned text? if you want to test the translation value or that the text is presented I suggest working with the actual values using the translation objects.

**Comment by stephengeorgewest** [comment] 2021-04-16 18:38
Sorry, I missed @krzyhan's response. And didn't realize until this latest comment. Adding config to the useValue worked for me.

I'm not sure obout @iiceman40's use case, but I wasn't testing the mocked returned text, but it was just throwing the error when I provided the mock translator, so the component would runfor tests. I was confused since the `providers: [provideMockTranslate()]` seemed to work, until combined with the `imports: [getTranslocoTestingModule()]`. It looks like we use the import for the translate pipes in templates, and the provide for the service. Is the `getTranslocoModule` mentioned in the documentation intended to work for both [in template via pipe] and [in component via service] translations? The codebase that I started working with has about 75 uses of `imports: [getTranslocoTestingModule]` to 25 uses of `providers: [provideMockTranslate]`.

**Comment by shaharkazaz** [comment] 2021-04-16 19:21
@stephengeorgewest `getTranslocoTestingModule` should take care of what you need.
`provideMockTranslate` isn't part of the Transloco official lib. seems like it was made to mock the `TranslocoService` but our exported module takes care of that for you. (from v2.20.0)

**Closed** 2021-04-16 21:35 UTC
Labels: needs reproduction
