### ISSUE TITLE
Weird error using TranslocoMessageFormatModule (about message format)

### ISSUE THREAD

**Issue by timhecker** [ngneat/transloco#350] opened 2020-09-21 11:18 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I run locally my project, this compiles, but with this error:

![Schermata 2020-09-21 alle 13 14 38](https://user-images.githubusercontent.com/3533765/93760538-7de22080-fc0c-11ea-804c-cfd9af78b43d.png)

## Expected behavior

Working with TranslocoMessageFormatModule as documented on https://ngneat.github.io/transloco/docs/plugins/message-format/

## Minimal reproduction of the problem with instructions

this is my `transloco-root.module.ts`:

```javascript
import { HttpClient } from '@angular/common/http'
import {
  TRANSLOCO_LOADER,
  Translation,
  TranslocoLoader,
  TRANSLOCO_CONFIG,
  translocoConfig,
  TranslocoModule
} from '@ngneat/transloco'
import { Injectable, NgModule } from '@angular/core'
import { environment } from '../environments/environment'
import { Observable } from 'rxjs'
import { TranslocoMessageFormatModule } from '@ngneat/transloco-messageformat'

@Injectable({ providedIn: 'root' })
export class TranslocoHttpLoader implements TranslocoLoader {
  constructor(private http: HttpClient) {}

  getTranslation(lang: string): Observable<any> {
    return this.http.get<Translation>(`/assets/i18n/${lang}.json`)
  }
}

export interface Lang {
  key: string
  label: string
}

export const mainLangs: string[] = ['en', 'it']
export const mainCompleteLangs: Lang[] = [
  { key: 'en', label: 'english' },
  { key: 'it', label: 'italiano' }
]

@NgModule({
  imports: [
    TranslocoMessageFormatModule.init({
      locales: ['en-GB', 'it-IT']
    })
  ],
  exports: [TranslocoModule],
  providers: [
    {
      provide: TRANSLOCO_CONFIG,
      useValue: translocoConfig({
        availableLangs: mainLangs,
        defaultLang: 'en',
        reRenderOnLangChange: true,
        prodMode: environment.production
      })
    },
    { provide: TRANSLOCO_LOADER, useClass: TranslocoHttpLoader }
  ]
})
export class TranslocoRootModule {}
```

Any idea or suggestions?
Thanks

## Environment

<pre><code>
Angular version: 10.1.0
@ngneat/transloco: ^2.19.1
@ngneat/transloco-messageformat: ^1.3.0
messageformat: ^2.3.0

Browser:
- [x ] Chrome (desktop) version 85
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.18.2  
- Platform:  Mac

</code></pre>

**Comment by itayod** [comment] 2020-10-05 12:02
Hi @timhecker I couldn't reproduce it on my local pc, could you please upload a reproduction project to stackblitz/github?

**Comment by timhecker** [comment] 2020-10-08 07:27
Sorry @itayod I switch project & I have no time now. I'm going to try again in the next weeks. Thanks.

**Comment by shaharkazaz** [comment] 2020-10-08 07:59
@timhecker ok so I'm closing this. 
Feel free to re-open when you have a reproduction 🙂

**Closed by shaharkazaz** 2020-10-08 07:59 UTC
