### ISSUE TITLE
Doc site is down

### ISSUE THREAD

**Issue by MussaratAziz** [ngneat/transloco#655] opened 2023-05-15 08:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

No

### Current behavior

Hi, doc site is down. Any update on that? Thanks

### Expected behavior

Should be able to view docs.

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://ngneat.github.io/transloco/docs/translation-in-the-template/

### Please provide the environment you discovered this bug in

```markdown
Transloco: 
Angular: 
Node: 
Package Manager: 
OS:
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment] 2023-05-15 09:07
@MussaratAziz The site sees to be up.
Please share more information.
<img width="1076" alt="image" src="https://github.com/ngneat/transloco/assets/17194830/3707dfc4-9220-471a-aef4-d73c55d35b3b">

**Comment by ottarhenanger** [comment] 2023-05-15 12:48
The doc site seem to have been down for days:

![image](https://github.com/ngneat/transloco/assets/981641/e99f20b8-00bc-4edb-94ae-2e72621ab972)

**Comment by shaharkazaz** [comment] 2023-05-15 14:29
There was an issue with some SSH error but it was fixed a few days ago.
I can access the site.
Can you provide some more information? (VPN, firewall? etc)

**Comment by ottarhenanger** [comment] 2023-05-15 14:39
Looks like the problem is either related to my Win11 installation or local WiFi router. Works when connected using my mobile network, but not when via my Wifi connection.

**Comment by shaharkazaz** [comment] 2023-05-15 14:43
@ottarhenanger See [this comment](https://github.com/ngneat/transloco/issues/643#issuecomment-1541778471)

**Comment by shaharkazaz** [comment] 2023-05-16 13:19
IDK what to say, I can access the site and I also asked some people to try and it worked for them.
Without understanding what's the diff from your attempt I'm not sure what I can do...

**Comment by blaropal** [comment] 2023-05-16 15:32
I get an SSL issue when trying to access the site.

![image](https://github.com/ngneat/transloco/assets/9976788/5c609751-2468-4f36-afc0-54392d27b7bf)

**Comment by shaharkazaz** [comment] 2023-05-16 20:17
One of you is welcome to investigate and open a PR/ instruct me on how to resolve this issue for you. I don't have that problem and there isn't much information I can work with.

**Comment by shaharkazaz** [comment] 2023-06-01 06:17
I'm redeploying the site maybe it will help. 
I'd appreciate it if someone who has the issue will look into it as I can't reproduce 🙏

**Comment by ahernd2** [comment] 2023-06-06 09:04
Its still down for me when on work VPN, but works off VPN. Im not sure what changed either, possibly some cert issue along the way

**Comment by shaharkazaz** [comment] 2023-06-08 08:57
@ahernd2 I also tried accessing the site via 2 different VPNs worked on both

**Comment by lflewwelling** [comment] 2023-06-19 22:54
I have an asus router and it uses trend micro to check URLs. This is resulting in the following if I use HTTP in the URL. 
![image](https://github.com/ngneat/transloco/assets/89599028/13effa10-d23e-437c-84ca-04e21a06acba)

When testing on Trend Micro's site I get the following: 
![image](https://github.com/ngneat/transloco/assets/89599028/28b79ea5-8953-4ca6-9935-d12f2bef9187)

**Comment by lflewwelling** [comment] 2023-06-19 23:05
Testing with VirusTotal.com I get the following 
![image](https://github.com/ngneat/transloco/assets/89599028/b3c2c227-4cec-4d39-acda-3281c37ec4b8)

**Comment by shaharkazaz** [comment] 2023-06-20 06:41
@lflewwelling Thanks for sharing these. I don't know why, but at some point, some of these tools started to mark the doc site as malicious.
I submitted a request to G-Data to re-evaluate the site.
The only way to mitigate this is when encountering try to submit a revelation form.
Obviously, there is no malicious code here (don't trust me, look for yourself) and the domain is managed by GitHub pages.

**Comment by paslavsky** [comment] 2023-06-26 06:12
Same with https://global.sitesafety.trendmicro.com/result.php

**Comment by ahernd2** [comment] 2023-06-29 15:25
This seems to be fixed now on my end at least

**Comment by shaharkazaz** [comment] 2023-06-29 16:16
Can everyone else please update? I submitted requests to all the sites posted here 🙏

**Comment by paslavsky** [comment] 2023-06-29 19:35
Works fine for me

**Comment by lflewwelling** [comment] 2023-06-29 19:37
Yes, @shaharkazaz this works now.

**Comment by shaharkazaz** [comment] 2023-06-29 19:48
@MussaratAziz is the issue resolved on your end?

**Comment by MussaratAziz** [comment] 2023-07-04 16:43
![image](https://github.com/ngneat/transloco/assets/6059505/9c65f1db-d428-44f7-a28b-5ec709a8a5c5)
:( not yet sorry.

**Comment by shaharkazaz** [comment] 2023-07-04 16:48
@MussaratAziz I need some information, as you can see when provided, we can resolve :)

**Comment by shaharkazaz** [comment] 2023-07-31 07:29
@MussaratAziz Closing this as it's working for most users if you can provide further information to why the site is blocked on your end feel free to reopen and I'll try to resolve

**Closed by shaharkazaz** 2023-07-31 07:29 UTC
Labels: documentation, help wanted, needs reproduction
