### ISSUE TITLE
"Member t is not callable" linting error

### ISSUE THREAD

**Issue by alxv2016** [ngneat/transloco#194] opened 2019-12-10 15:49 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Not sure what's going on as I don't get any errors and translations work, but vsCode is throwing me
a linting error when I use the structural directive 

## Expected behavior
shouldn't throw any linting errors 

## Minimal reproduction of the problem with instructions

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem, for that you could use our [stackblitz example](https://stackblitz.com/edit/transloco-example)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pelssersconsultancy** [comment] 2019-12-10 18:36
That has to do with the angular language service plugin if I remember correct.

https://github.com/angular/angular/issues/16643

**Comment by itayod** [comment] 2019-12-10 18:40
duplicate of #177

**Closed** 2019-12-10 18:40 UTC
