### ISSUE TITLE
Feature(scope): Support Angular v14

### ISSUE THREAD

**Issue by akikesulahti** [ngneat/transloco#580] opened 2022-07-20 23:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco

### Is your feature request related to a problem? Please describe

Transloco Schematics do not work with new Angular 14 project.
Steps to reproduce:
1. Install latest Angular CLI `npm install -g @angular/cli`
2. Create new Angular v14 project `ng new my-first-project`
3. Try to add Transloco `ng add @ngneat/transloco`
4. Installation will fail to error `Cannot read properties of undefined (reading 'projectType')`

```
$ ng add @ngneat/transloco
Skipping installation: Package already installed
? 🌍 Which languages do you need? en, es
? 🚀 Are you working with server side rendering? No
Cannot read properties of undefined (reading 'projectType')
```

### Describe the solution you'd like

Add support to Angular v14.
(Something schematics related probably broke in latest releases)

### Describe alternatives you've considered

```markdown
Alternative provide guide how to add Transloco without schematics to Angular v14.
```

### Additional context

Not sure if related but `angular-cli` version 14.0.0 had breaking change with `@angular-devkit/schematics-cli` that says `camel case arguments are no longer allowed.`
https://github.com/angular/angular-cli/blob/main/CHANGELOG.md#1400-2022-06-02

### I would like to make a pull request for this feature

No

**Comment by b-legrand** [comment] 2022-07-27 12:32
i'm having the same issue, it seems the default project cannot be detected anymore.

using the `--project` argument fixes it : 
```
ng new i18n-transloco-test
cd i18n-transloco-test
ng add @ngneat/transloco --project=i18n-transloco-test
```

**Comment by b-legrand** [comment] 2022-07-27 12:42
[getProject](https://github.com/ngneat/transloco/blob/master/libs/transloco-schematics/src/utils/projects.ts#L31) method relies on the `defaultProject` attribute, which has been deprecated : https://github.com/angular/angular-cli/blob/main/CHANGELOG.md#angularcli-8 

> The `defaultProject` workspace option has been deprecated. The project to use will be determined from the current working directory.

Not sure what the fix should be... using the folder name instead ?

**Comment by b-legrand** [comment] 2022-07-27 14:12
I proposed a pull-request to implement this recommendation : https://github.com/angular/angular-cli/issues/23470#issuecomment-1172240384

**Comment by rijad992** [comment] 2022-08-05 09:19
passing project argument does not seem to work for me.

**Comment by xrasod** [comment] 2022-08-08 11:52
Passing project path worked for me. Thanks for the solution!

**Comment by Panix123** [comment] 2022-08-10 06:43
> i'm having the same issue, it seems the default project cannot be detected anymore.
> 
> using the `--project` argument fixes it :
> 
> ```
> ng new i18n-transloco-test
> cd i18n-transloco-test
> ng add @ngneat/transloco --project=i18n-transloco-test
> ```

You are my hero, thank you.... was searching for half a day yesterday.

**Comment by jongbonga** [comment] 2022-08-12 15:11
> passing project argument does not seem to work for me.

Same here unfortunatly

**Comment by rijad992** [comment] 2022-08-14 05:18
> > passing project argument does not seem to work for me.
> 
> Same here unfortunately

Try adding:

`defaultProject: "--your-project-name--"`

to your angular.json
It worked for me.

**Comment by hvma411** [comment] 2022-09-25 19:16
> > > passing project argument does not seem to work for me.
> > 
> > 
> > Same here unfortunately
> 
> Try adding:
> 
> `defaultProject: "--your-project-name--"`
> 
> to your angular.json It worked for me.

"defaultProject" is deprecated and it does not help to solve it

**Comment by byjokese** [comment] 2022-11-24 16:39
Does that solution apply to Angular 15, also? Has anyone tested it with Angular 15?

**Comment by enrique-lozano** [comment] 2022-12-09 13:17
Some help about this?  @shaharkazaz 

The problem persists and passing the `--project` flag doesn't work in my case either. The fact that the library is not compatible with the last two versions of Angular should have max priority.

**Comment by shaharkazaz** [comment] 2022-12-09 13:45
@enrique-lozano There is a valid workaround suggested by @b-legrand.
Until a fix is merged I'll update the docs to pass the project value to the command.
I'm too busy to push this project as much as I wanted to, we are trying to get sponsorship to free more time not just for this project but for all the others as well.
But if you take a look at our [sponsorship page](https://github.com/sponsors/ngneat) you can see how this is going 😞

**Comment by shaharkazaz** [comment] 2022-12-09 13:56
Docs have been updated. @b-legrand Thank you, I'll also try to push you PR forward, see the comment I left.

**Comment by shaharkazaz** [comment] 2022-12-10 07:01
Should be fixed in v4.1.2. Thanks again @b-legrand.
Can @akikesulahti or anyone else in this thread please verify?

**Comment by byjokese** [comment] 2022-12-10 11:21
Hi @shaharkazaz, did a quick test with the new version `v4.1.2`. And the installation process seems to work (haven't test the app itself yet).

I was using:
![image](https://user-images.githubusercontent.com/5951126/206852357-a798b36d-7f4f-4431-9a00-6f8d971c85bf.png)

With the new version:
![image](https://user-images.githubusercontent.com/5951126/206852341-fcf6a623-d1cd-4db0-9683-ba8d6848b196.png)

With the previous version:
![image](https://user-images.githubusercontent.com/5951126/206852396-c073f2bb-8c0d-488a-8462-da9ab2837b8c.png)


Seems good so far, thanks for the update. Will check the app now.

**Comment by byjokese** [comment] 2022-12-10 12:04
Just as a Heads-up, In Angular 15 `@angular/cli` does no longer generate the environment files. And `transloco-root.module.ts`, does always import it, so for new applications it won't compile out of the box. They removed it, because it was only used for `enableProdMode`, but in Angular 15:

> the enableProdMode function call has been removed in main.ts. It was only used for JiT mode, which is not really used anymore. In AoT mode, the CLI already sets ngDevMode when building in production mode, which has the same purpose.

There's a PR open for adding them: https://github.com/angular/angular-cli/pull/24409 that solves https://github.com/angular/angular-cli/issues/24381.

**Comment by shaharkazaz** [comment] 2022-12-10 21:24
@byjokese Thanks for the heads-up, new projects will now use the `isDevMode` function instead. You can see [here](https://github.com/ngneat/transloco/commit/e4bc6c91cb04d8e2ff41269abb963f1c6eed0c93)

**Comment by shaharkazaz** [comment] 2022-12-11 05:59
@akikesulahti  I'm closing this as @byjokese verified that the issue is resolved.
Please feel free to reopen if something is still not working.

**Closed by shaharkazaz** 2022-12-11 05:59 UTC
