### ISSUE TITLE
Upgrade to v2 with schematics broke nearly all my views

### ISSUE THREAD

**Issue by maxime1992** [ngneat/transloco#111] opened 2019-10-03 05:43 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
⬆️ Starting v2 upgrade script ⬆️
Done! Welcome to Transloco v2 😎
Nothing to be done.
```

Said nothing to be done but it definitely did something:

![image](https://user-images.githubusercontent.com/4950209/66101777-f5f0aa00-e5a7-11e9-83bc-a91cd024f64d.png)

![image](https://user-images.githubusercontent.com/4950209/66101799-09037a00-e5a8-11e9-878c-b6ebcf6805e8.png)

And the views appear to be broken

## Expected behavior

Schematics shouldn't break the views

## Minimal reproduction of the problem with instructions

Try to upgrade with the schematics?

Here's a component I've got that was broken after the upgrade:

```
<ng-container *transloco="let t">
  <app-hero
    [title]="'Albi Eco Race'"
    [subTitle]="t.editionNumber"
    [buttonText]="t.static.registration"
    buttonUrl="/register"
    [text]="t.dateAndWhere"
  ></app-hero>

  <app-promo [isSmallText]="true"></app-promo>

  <app-block [title]="'What people say'" theme="primary"><app-what-people-say></app-what-people-say></app-block>

  <app-block class="register-block">
    <button mat-raised-button color="accent" routerLink="register">{{ t.static.iWishToParticipate }}</button>
  </app-block>
</ng-container>
```

## Environment

<pre><code>
Angular version: 8.2.0

 
For Tooling issues:
- Node version: 12.4
- Platform:  Linux

Others:

</code></pre>

**Comment by shaharkazaz** [comment] 2019-10-03 07:55
@maxime1992 Thanks for the report! I found the issue and I believe I have fixed it, can you try it again and tell me how it goes? it now available in v2.0.2

**Comment by maxime1992** [comment] 2019-10-03 20:46
@shaharkazaz it did work but noticed some of them were not taken into account for some reason :man_shrugging: (with nothing special for them) and the ones that were using the syntax:

```
{{ t.static.availableDocuments | translocoParams: { nbDocuments: category.documents.length } }}
```

were not done either. Not really a huge issue I did it but I thought you may want to know :) 

Thanks for your help, if you're happy with the above feel free to close the issue.

**Comment by shaharkazaz** [comment] 2019-10-03 21:15
@maxime1992 thanks again for the feedback! 
I'm happy to hear that the issue is mostly resolved, it would be great if you could share all the places the script missed with the templates.

**Comment by shaharkazaz** [comment] 2019-10-04 14:21
@maxime1992 The main issue was resolved, so I'm closing this.
let's take this to gitter or continue here if you prefer to handle the script's misses 🙂

**Closed by shaharkazaz** 2019-10-04 14:21 UTC
Labels: bug
