### ISSUE TITLE
Lazy loading with scope names only partially works

### ISSUE THREAD

**Issue by bjornharvold** [ngneat/transloco#69] opened 2019-09-07 05:33 UTC
## I'm submitting a...

<pre><code>
[x] Bug report
</code></pre>

## Current behavior

I'm converting from ngx-translate. My lazy loaded keys look like: 'OTA.TITLE'. OTA being the lazy module namespace.

(BTW the migrate tool missed a few 'translate.get' and '| translate' commands)

I set up the config on the lazy module. 
`providers: [{provide: TRANSLOCO_SCOPE, useValue: 'ota'}]`

In AppModule i set
```
scopeMapping: {
  ota: 'OTA'
}
```

In my lazy component I write:
`{{ 'OTA.TITLE' | transloco | uppercase }}`

I get an error.

However, it works if I remove the scopeMapping and write
`{{ 'ota.TITLE' | transloco | uppercase }}`

It also works if I write:
```
scopeMapping: {
  ota: 'someName'
}
```

And then write:
`{{ 'someName.TITLE' | transloco | uppercase }}`

But straight uppercase OTA does not work.

## Environment

<pre><code>
Angular CLI: 8.3.3
Node: 12.9.1
OS: darwin x64
Angular: 8.2.5
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.3
@angular-devkit/build-angular      0.803.3
@angular-devkit/build-ng-packagr   0.803.3
@angular-devkit/build-optimizer    0.803.3
@angular-devkit/build-webpack      0.803.3
@angular-devkit/core               8.3.3
@angular-devkit/schematics         8.3.3
@angular/cdk                       8.1.4
@angular/cli                       8.3.3
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.1.4
@angular/pwa                       0.803.3
@ngtools/webpack                   8.3.3
@schematics/angular                8.3.3
@schematics/update                 0.803.3
ng-packagr                         5.5.0
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2

Browser:
- [X] Chrome (desktop) version XX
</code></pre>

**Comment by shaharkazaz** [comment] 2019-09-07 07:11
What version of Transloco are you using?
If it's the latest, can you provide which cases the migration script missed the switch? 

About the scope I'll check it.

**Comment by bjornharvold** [comment] 2019-09-07 08:05
Hi @shaharkazaz 

I will run the migration again once the scope is working.

Basically fringe cases where the variable is partially dynamic. E.g. {{'test.' + name | translate}}

**Comment by bjornharvold** [comment] 2019-09-07 08:14
Regarding scope... In your documentation you state the default scope is upper cased. But that does not seem to be the case. I tried all kinds of upper case scopes and none work.

**Comment by shaharkazaz** [comment] 2019-09-07 08:50
@bjornharvold 
I see what you mean, that's a mistake in the docs that I will update now.
All scopes names are camelCased, which means that if your scope name is `ota` it will remain `ota`.

I understand that scope mapping to uppercase doesn't work for you? (if that's what you need).

About the migration, I have tested the case you have shown here and it seems ok, maybe we can take it privately on gitter in order to keep the focus of this issue relevant? 🙂

**Comment by shaharkazaz** [comment] 2019-09-07 09:37
@bjornharvold 
I just published v1.7.4 can you verify that the issue is resolved? 🙂 
I would also appreciate it if we can try to resolve the issues you had with the migration.

**Comment by bjornharvold** [comment] 2019-09-08 03:39
Here are the errors I get after migrating.

```
ERROR in src/app/app.component.ts:43:20 - error TS2339: Property 'addLangs' does not exist on type 'TranslocoService'.

43     this.translate.addLangs(Language.getSupportedLanguageCodes());
                      ~~~~~~~~
src/app/app.component.ts:44:20 - error TS2339: Property 'use' does not exist on type 'TranslocoService'.

44     this.translate.use(Language.getDefaultLanguage());
                      ~~~
src/app/app.module.ts:11:10 - error TS2300: Duplicate identifier 'TranslocoModule'.

11 import { TranslocoModule } from '@ngneat/transloco';
            ~~~~~~~~~~~~~~~
src/app/app.module.ts:38:10 - error TS2300: Duplicate identifier 'TranslocoModule'.

38 import { TranslocoModule, TRANSLOCO_CONFIG, TranslocoConfig } from '@ngneat/transloco';
            ~~~~~~~~~~~~~~~
src/app/channel/root/root.component.ts:12:20 - error TS2339: Property 'use' does not exist on type 'TranslocoService'.

12     this.translate.use('en');
                      ~~~
src/app/engine/root/root.component.ts:12:20 - error TS2339: Property 'use' does not exist on type 'TranslocoService'.

12     this.translate.use('en');
                      ~~~
src/app/greendex/configuration/configuration.component.ts:64:29 - error TS2339: Property 'get' does not exist on type 'TranslocoService'.

64       this.translateService.get('GREENDEX_QUESTION.' + this.form.get('category').value + '.' + this.form.get('sort').value).pipe(
                               ~~~
src/app/hotel/list/list.component.ts:93m172:24 - error TS2339: Property 'get' does not exist on type 'TranslocoService'.

172         this.translate.get('HOTEL_CODE_CONTEXT.' + k).pipe(
                           ~~~
src/app/ota/root/root.component.ts:12:20 - error TS2339: Property 'use' does not exist on type 'TranslocoService'.

12     this.translate.use('en');
                      ~~~
src/app/report/booking-report/booking-report.component.ts:217:22 - error TS2339: Property 'get' does not exist on type 'TranslocoService'.

217       this.translate.get(cancelOption.text).subscribe(txText => {
                         ~~~
src/app/report/channel-communication-ext-report/channel-communication-ext-report.component.ts:205:24 - error TS2339: Property 'get' does not exist on type 'TranslocoService'.

205         this.translate.get('HCC.' + HotelCodeContext[n]).pipe(
                           ~~~
src/app/report/channel-communication-ext-report/channel-communication-ext-report.component.ts:218:24 - error TS2339: Property 'get' does not exist on type 'TranslocoService'.

218         this.translate.get('CHANNEL_COMMUNICATION.PHASES.' + ChannelCommunicationExtPhase[n]).pipe(
                           ~~~
src/app/report/hotel-report/hotel-report.component.ts:208:24 - error TS2339: Property 'get' does not exist on type 'TranslocoService'.

208         this.translate.get(HotelInternalStatus[n]).pipe(
                           ~~~
src/app/report/hotel-report/hotel-report.component.ts:218:22 - error TS2339: Property 'get' does not exist on type 'TranslocoService'.

218       this.translate.get('EXTERNAL_STATUS_' + status.value).pipe(
                         ~~~
src/app/review/configuration/configuration.component.ts:57:29 - error TS2339: Property 'get' does not exist on type 'TranslocoService'.

57       this.translateService.get('REVIEW_QUESTION.' + this.form.get('category').value + '.' + this.form.get('sort').value).pipe(
                               ~~~
src/app/secure/charity-overview-chart/charity-overview-chart.component.ts:33:35 - error TS2339: Property 'get' does not exist on type 'TranslocoService'.

33             this.translateService.get(iPieData.category).pipe(
                                     ~~~
src/app/secure/hotel-overview-chart/hotel-overview-chart.component.ts:39:35 - error TS2339: Property 'get' does not exist on type 'TranslocoService'.

39             this.translateService.get(iChart.categoryField).pipe(
                                     ~~~
src/app/third-party/root/root.component.ts:12:20 - error TS2339: Property 'use' does not exist on type 'TranslocoService'.

12     this.translate.use('en');
```

**Comment by bjornharvold** [comment] 2019-09-08 03:53
Here are | translate directives that didn't get translate. See attached.

<img width="901" alt="Screen Shot 2019-09-08 at 10 52 40 AM" src="https://user-images.githubusercontent.com/641791/64483070-d378a480-d226-11e9-8ff5-a08151928cfa.png">

**Comment by bjornharvold** [comment] 2019-09-08 03:59
I can confirm that scoped upper case names are working. This is great because I would assume most ngx-translate users and folks using Pascal's earlier translate module are writing keys as all upper case and not camelCase. That would be a pretty big deal for adoption.

**Comment by bjornharvold** [comment] 2019-09-08 03:59
Thank you for the quick turnaround @shaharkazaz

**Comment by bjornharvold** [comment] 2019-09-08 05:59
Regarding migration: this.translate.currentLang does not migrate to this.translate.getActiveLang

**Comment by bjornharvold** [comment] 2019-09-08 06:12
Another thing I noticed: Migration doesn't change this.translate.use(newLang) to this.translate.setActiveLang(newLang)

**Comment by shaharkazaz** [comment] 2019-09-08 06:37
@bjornharvold you can read what is currently supported by the migration script in the migration [README](https://github.com/ngneat/transloco/blob/master/schematics/migration.md).
I'm closing this issue, please let's take this privately so we can improve the migration script 🙂

**Closed by shaharkazaz** 2019-09-08 06:37 UTC
